//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BacklightServices_h
#define BacklightServices_h

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <os/lock.h>

#import "BLSAlwaysOnFrameSpecifier.h"
#import "BLSAlwaysOnPeriodicTimeline.h"
#import "BLSAlwaysOnTimeline.h"
#import "BLSAlwaysOnTimelineEntry.h"
#import "BLSAlwaysOnTimelineEntrySpecifier.h"
#import "BLSAlwaysOnTimelineUnconfiguredEntry.h"

#endif /* BacklightServices_h */
