//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BacklightServices_h
#define BacklightServices_h

#include <Foundation/Foundation.h>
#include <UIKit/UIKit.h>
#include <os/lock.h>

#include "BLSUpdateFidelity.h"
#include "BLSAlwaysOnFrameSpecifier.h"
#include "BLSAlwaysOnPeriodicTimeline.h"
#include "BLSAlwaysOnTimeline.h"
#include "BLSAlwaysOnTimelineEntry.h"
#include "BLSAlwaysOnTimelineEntrySpecifier.h"
#include "BLSAlwaysOnTimelineUnconfiguredEntry.h"

#endif /* BacklightServices_h */
