//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAlwaysOnFrameSpecifier_h
#define BLSAlwaysOnFrameSpecifier_h

#include "BLSUpdateFidelity.h"
#include <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface BLSAlwaysOnFrameSpecifier : NSObject <NSCopying> {
    os_unfair_lock _lock;
}

@property BLSUpdateFidelity grantedFidelity;
@property (readonly) NSArray *entrySpecifiers;
@property (readonly) NSDateInterval *presentationInterval;
@property (readonly) BLSUpdateFidelity requestedFidelity;

/* class methods */
+ (id)loggingStringForPresentationInterval:(id)interval;
+ (id)shortLoggingStringForPresentationInterval:(id)interval;

/* instance methods */
- (instancetype)initWithTimelineEntrySpecifiers:(id)specifiers presentationInterval:(id)interval;
- (id)entrySpecifierForTimelineIdentifier:(id)identifier;
- (long long)compare:(id)compare;
- (id)correctedSpecifierWithNextSpecifier:(id)specifier;
- (NSString *)description;
- (NSString *)debugDescription;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)zone;

@end

NS_ASSUME_NONNULL_END

#endif /* BLSAlwaysOnFrameSpecifier_h */
