//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAlwaysOnTimelineEntrySpecifier_h
#define BLSAlwaysOnTimelineEntrySpecifier_h

#include "BLSAlwaysOnTimelineEntry.h"
#include "BLSUpdateFidelity.h"
#include <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface BLSAlwaysOnTimelineEntrySpecifier : NSObject <NSCopying> {
    /* instance variables */
    os_unfair_lock _lock;
}

@property BOOL didChange;
@property BLSUpdateFidelity grantedFidelity;
@property BLSUpdateFidelity requestedFidelity;
@property (readonly) BLSAlwaysOnTimelineEntry *timelineEntry;
@property (readonly) double percentComplete;
@property (readonly) BLSAlwaysOnTimelineEntry *previousTimelineEntry;

/* instance methods */
- (instancetype)initWithTimelineEntry:(id)entry percentComplete:(double)complete previousTimelineEntry:(id)entry didChange:(_Bool)change;
- (long long)compare:(id)compare;
- (NSString *)description;
- (void)appendFidelityToTarget:(id)target;
- (NSString *)debugDescription;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)zone;

@end

NS_ASSUME_NONNULL_END

#endif /* BLSAlwaysOnTimelineEntrySpecifier_h */
