//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAlwaysOnTimeline_h
#define BLSAlwaysOnTimeline_h

#include "BLSUpdateFidelity.h"
#include <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface BLSAlwaysOnTimeline : NSObject {
    /* instance variables */
    id /* block */ _configureEntryBlock;
}

@property (readonly, nonatomic) id <NSObject, NSCopying> identifier;

/* class methods */
+ (id)emptyTimelineWithIdentifier:(id)identifier;
+ (id)timelineWithPerMinuteUpdateFrequency:(long long)frequency identifier:(id)identifier configure:(id /* block */)configure;
+ (id)everyMinuteTimelineWithIdentifier:(id)identifier configure:(id /* block */)configure;
+ (id)timelineWithUpdateInterval:(double)interval startDate:(id)date identifier:(id)identifier configure:(id /* block */)configure;
+ (id)timelineWithEntries:(id)entries identifier:(id)identifier configure:(id /* block */)configure;
+ (NSRange)rangeOfEntries:(id)entries forDateInterval:(id)interval shouldIncludePrevious:(_Bool)previous;
+ (id)constructFrameSpecifiersForTimelines:(id)timelines dateInterval:(id)interval shouldConstructStartSpecifier:(_Bool)specifier framesPerSecond:(double)second previousSpecifier:(id)specifier;
+ (BLSUpdateFidelity)requestedFidelityForTimelines:(id)timelines inDateInterval:(id)interval;

/* instance methods */
- (id)initWithIdentifier:(id)identifier configure:(id /* block */)configure;
- (NSString *)description;
- (id)configureEntry:(id)entry previousEntry:(id)entry;
- (id)configureEntries:(id)entries previousEntry:(id)entry;
- (BLSUpdateFidelity)requestedFidelityForStartEntryInDateInterval:(id)interval withPreviousEntry:(id)entry;
- (id)unconfiguredEntriesForDateInterval:(id)interval previousEntry:(id)entry;
- (BLSUpdateFidelity)estimatedFidelityForPresentationTime:(id)time nextPresentationTime:(id)time;

@end

NS_ASSUME_NONNULL_END

#endif /* BLSAlwaysOnTimeline_h */
