//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAlwaysOnTimelineEntry_h
#define BLSAlwaysOnTimelineEntry_h

#include "BLSUpdateFidelity.h"
#include <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface BLSAlwaysOnTimelineEntry : NSObject <NSCopying, NSMutableCopying>

@property (nonatomic) BLSUpdateFidelity requestedFidelity;
@property (nonatomic) _Bool animated;
@property (nonatomic) double duration;
@property (retain, nonatomic) id <NSObject> userObject;
@property (retain, nonatomic) id <NSObject, NSCopying> timelineIdentifier;
@property (readonly, nonatomic) NSDate *presentationTime;

/* class methods */
+ (id)loggingStringForPresentationTime:(id)time;
+ (id)shortLoggingStringForPresentationTime:(id)time;

/* instance methods */
- (instancetype)initWithPresentationTime:(id)time requestedFidelity:(BLSUpdateFidelity)fidelity animated:(_Bool)animated duration:(double)duration timelineIdentifier:(id)identifier userObject:(id)object;
- (long long)compare:(id)compare;
- (NSString *)description;
- (NSString *)debugDescription;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (_Bool)isAnimated;

@end

NS_ASSUME_NONNULL_END

#endif /* BLSAlwaysOnTimelineEntry_h */
