//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAssertionAcquisitionObserver_h
#define BLSAssertionAcquisitionObserver_h
@import Foundation;

#include "BLSAssertionObserving-Protocol.h"

@class NSObject, NSString;

@interface BLSAssertionAcquisitionObserver : NSObject <BLSAssertionObserving> {
    /* instance variables */
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
    id /* block */ _lock_completion;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)observerWithCompletion:(id /* block */)completion;

/* instance methods */
- (void)assertionWasAcquired:(id)acquired;
- (void)assertion:(id)assertion didFailToAcquireWithError:(id)error;
- (void)assertion:(id)assertion didCancelWithError:(id)error;

@end

#endif /* BLSAssertionAcquisitionObserver_h */
