//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAttribute_h
#define BLSAttribute_h
@import Foundation;

#include "BSXPCCoding-Protocol.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSObject, NSString;

@interface BLSAttribute : NSObject <BSXPCCoding, NSCopying, NSSecureCoding>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)init;
- (_Bool)canBePaused;
- (_Bool)isEqual:(id)equal;
- (_Bool)checkEntitlementSourceForRequiredEntitlements:(id)entitlements error:(out id *)error;
- (_Bool)checkEntitlementSource:(id)source forSingleEntitlement:(id)entitlement error:(out id *)error;
- (id)errorForMissingEntitlement:(id)entitlement inSource:(id)source;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* BLSAttribute_h */
