//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAssertion_h
#define BLSAssertion_h
@import Foundation;

#include "BLSAssertionAcquisitionObserver.h"
#include "BLSAssertionDescriptor.h"
#include "BLSAssertionIdentifier.h"
#include "BLSAssertionService-Protocol.h"
#include "BLSAssertionServiceResponding-Protocol.h"
#include "BSCancellable-Protocol.h"
#include "BSInvalidatable-Protocol.h"

@class NSArray, NSHashTable, NSObject, NSString;

@interface BLSAssertion : NSObject <BLSAssertionServiceResponding, BSCancellable, BSInvalidatable> {
    /* instance variables */
    BLSAssertionAcquisitionObserver *_acquisitionObserver;
    NSHashTable *_observers;
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
    _Bool _lock_acquired;
    _Bool _lock_paused;
    _Bool _lock_everPaused;
    _Bool _lock_invalidated;
    unsigned long long _lock_localState;
    double _lock_accumulatedUnpausedDuration;
    unsigned long long _lock_requestedMachContinuousTime;
    unsigned long long _lock_acquiredMachContinuousTime;
    unsigned long long _lock_unpauseMachContinuousTime;
    unsigned long long _lock_canceledMachContinuousTime;
}

@property (retain) id <BLSAssertionService> service;
@property (readonly, copy, nonatomic) NSString *explanation;
@property (readonly, copy, nonatomic) NSArray *attributes;
@property (readonly, nonatomic) _Bool acquired;
@property (readonly, nonatomic) _Bool paused;
@property (readonly, nonatomic) _Bool active;
@property (readonly, nonatomic) BLSAssertionDescriptor *descriptor;
@property (retain, nonatomic) BLSAssertionIdentifier *identifier;
@property (readonly, nonatomic) unsigned long long acquisitionState;
@property (readonly, nonatomic) double activeDuration;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)acquireWithExplanation:(id)explanation observer:(id)observer attributes:(id)attributes;
+ (void)setDefaultService:(id)service;

/* instance methods */
- (id)initWithExplanation:(id)explanation attributes:(id)attributes;
- (void)dealloc;
- (_Bool)isAcquired;
- (_Bool)isPaused;
- (_Bool)isActive;
- (void)acquireWithObserver:(id)observer;
- (void)acquireWithCompletion:(id /* block */)completion;
- (void)cancel;
- (void)invalidate;
- (void)restartTimeoutTimer;
- (void)addObserver:(id)observer;
- (void)removeObserver:(id)observer;
- (oneway void)serviceDidAcquire;
- (oneway void)serviceFailedToAcquireWithError:(id)error;
- (oneway void)serviceDidPause;
- (oneway void)serviceDidResume;
- (oneway void)serviceWillCancel;
- (oneway void)serviceDidCancelWithError:(id)error;

@end

#endif /* BLSAssertion_h */
