//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAlwaysOnDateSpecifier_h
#define BLSAlwaysOnDateSpecifier_h
@import Foundation;





@class NSDate, NSObject, NSString;

@interface BLSAlwaysOnDateSpecifier : NSObject <NSCopying, NSSecureCoding, BSXPCCoding>

@property (readonly, nonatomic) NSDate *date;
@property (readonly, nonatomic) long long fidelity;
@property (readonly, nonatomic) id userObject;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithDate:(id)date fidelity:(long long)fidelity userObject:(id)object;
- (id)initWithDate:(id)date fidelity:(long long)fidelity;
- (id)newSpecifierWithMaxFidelity:(long long)fidelity;
- (id)bls_shortLoggingString;
- (id)bls_loggingString;
- (_Bool)isEqual:(id)equal;
- (long long)compare:(id)compare;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* BLSAlwaysOnDateSpecifier_h */
