//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAlwaysOnSession_h
#define BLSAlwaysOnSession_h
@import Foundation;

#include "BLSBacklightSceneEnvironment-Protocol.h"
#include "BLSFrameSpecifierModel.h"


@class NSObject, NSString;

@interface BLSAlwaysOnSession : NSObject <BSInvalidatable>

@property (retain) BLSFrameSpecifierModel *model;
@property (readonly, weak) id <BLSBacklightSceneEnvironment> environment;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithEnvironment:(id)environment;
- (void)invalidate;
- (id)specifierForPresentationDate:(id)date;
- (void)desiredFidelityForDateInterval:(id)interval timelines:(id)timelines withCompletion:(id /* block */)completion;
- (void)performFrameSpecifiersRequest:(id)request timelines:(id)timelines;

@end

#endif /* BLSAlwaysOnSession_h */
