//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightFBSSceneEnvironmentDiffActionDelegate_Protocol_h
#define BLSBacklightFBSSceneEnvironmentDiffActionDelegate_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol BLSBacklightFBSSceneEnvironmentDiffActionDelegate <NSObject>

@required

/* required instance methods */
- (void)performChangesWithTransitionContext:(id)context environmentDelta:(struct { unsigned int x0:1; unsigned int x1:1; unsigned int x2:1; unsigned int x3:1; unsigned int x4:1; })delta performActionsBlock:(id /* block */)block;

@optional

@end

#endif /* BLSBacklightFBSSceneEnvironmentDiffActionDelegate_Protocol_h */
