//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightProxy_Protocol_h
#define BLSBacklightProxy_Protocol_h
@import Foundation;

#include "BLSBacklightChangeRequestable-Protocol.h"
#include "BLSBacklightStateObservable-Protocol.h"

@protocol BLSBacklightProxy <BLSBacklightStateObservable, BLSBacklightChangeRequestable>

@required

@optional

@end

#endif /* BLSBacklightProxy_Protocol_h */
