//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightSceneEnvironmentUpdater_h
#define BLSBacklightSceneEnvironmentUpdater_h
@import Foundation;

#include "BLSBacklightSceneEnvironmentUpdating-Protocol.h"
#include "BLSBacklightSceneEnvironment_Private-Protocol.h"

@class NSObject, NSString;

@interface BLSBacklightSceneEnvironmentUpdater : NSObject <BLSBacklightSceneEnvironmentUpdating> {
    /* instance variables */
    id <BLSBacklightSceneEnvironment_Private> _environment;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithEnvironment:(id)environment;
- (void)updatedEnvironmentWithDelta:(struct { unsigned int x0:1; unsigned int x1:1; unsigned int x2:1; unsigned int x3:1; unsigned int x4:1; })delta backlightSceneUpdate:(id)update;
- (void)performDesiredFidelityRequest:(id)request;
- (void)performFrameSpecifiersRequest:(id)request;

@end

#endif /* BLSBacklightSceneEnvironmentUpdater_h */
