//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightFBSSceneEnvironment_h
#define BLSBacklightFBSSceneEnvironment_h
@import Foundation;

#include "BLSAlwaysOnFrameSpecifier.h"
#include "BLSAlwaysOnSession.h"
#include "BLSBacklightSceneEnvironmentUpdating-Protocol.h"
#include "BLSBacklightSceneEnvironment_Private-Protocol.h"
#include "BLSBacklightSceneVisualState.h"

@class FBSScene, NSDate, NSObject, NSString;
@protocol BLSBacklightSceneEnvironmentDelegate;

@interface BLSBacklightFBSSceneEnvironment : NSObject <BLSBacklightSceneEnvironment_Private> {
    /* instance variables */
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
}

@property (weak) FBSScene *fbsScene;
@property _Bool optsOutOfProcessAssertions;
@property (readonly) NSDate *presentationDate;
@property (retain) BLSAlwaysOnSession *alwaysOnSession;
@property _Bool animatingVisualState;
@property (retain) id <BLSBacklightSceneEnvironmentUpdating> updater;
@property (retain) id <BLSBacklightSceneEnvironmentDelegate> delegate;
@property (readonly, copy) NSString *identifier;
@property (readonly) _Bool delegateActive;
@property (readonly) BLSBacklightSceneVisualState *visualState;
@property (readonly) BLSAlwaysOnFrameSpecifier *frameSpecifier;
@property (readonly) _Bool liveUpdating;
@property (readonly) _Bool unrestrictedFramerateUpdates;
@property _Bool supportsAlwaysOn;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)createEnvironmentForFBSScene:(id)fbsscene;

/* instance methods */
- (id)initWithFBSScene:(id)fbsscene;
- (_Bool)isDelegateActive;
- (_Bool)isLiveUpdating;
- (_Bool)hasUnrestrictedFramerateUpdates;
- (void)invalidateAllTimelinesForReason:(id)reason;
- (_Bool)isAnimatingVisualState;
- (id)_FBSScene;
- (void)_setFBSScene:(id)fbsscene;

@end

#endif /* BLSBacklightFBSSceneEnvironment_h */
