//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightSceneEnvironment_Protocol_h
#define BLSBacklightSceneEnvironment_Protocol_h
@import Foundation;

#include "BLSAlwaysOnFrameSpecifier.h"
#include "BLSAlwaysOnSession.h"
#include "BLSBacklightSceneVisualState.h"
#include "NSObject-Protocol.h"

@class NSString;
@protocol BLSBacklightSceneEnvironmentDelegate;

@protocol BLSBacklightSceneEnvironment <NSObject>

@required

@property (retain) id <BLSBacklightSceneEnvironmentDelegate> delegate;
@property (readonly, copy) NSString *identifier;
@property (readonly) _Bool delegateActive;
@property (readonly) BLSBacklightSceneVisualState *visualState;
@property (readonly) BLSAlwaysOnFrameSpecifier *frameSpecifier;
@property (readonly) _Bool animatingVisualState;
@property (readonly) BLSAlwaysOnSession *alwaysOnSession;
@property (readonly) _Bool liveUpdating;
@property (readonly) _Bool unrestrictedFramerateUpdates;
@property _Bool supportsAlwaysOn;

/* required instance methods */
- (void)invalidateAllTimelinesForReason:(id)reason;
- (_Bool)isDelegateActive;
- (_Bool)isAnimatingVisualState;
- (_Bool)isLiveUpdating;
- (_Bool)hasUnrestrictedFramerateUpdates;

@optional

@end

#endif /* BLSBacklightSceneEnvironment_Protocol_h */
