//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightSceneUpdateBacklightRampResponse_h
#define BLSBacklightSceneUpdateBacklightRampResponse_h
@import Foundation;

@class BSActionResponse;

@interface BLSBacklightSceneUpdateBacklightRampResponse : BSActionResponse

@property (readonly, nonatomic) double rampDuration;

/* instance methods */
- (id)initWithRampDuration:(double)duration;

@end

#endif /* BLSBacklightSceneUpdateBacklightRampResponse_h */
