//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSDurationAttribute_h
#define BLSDurationAttribute_h
@import Foundation;

#include "BLSAttribute.h"


@class NSString;

@interface BLSDurationAttribute : BLSAttribute <BSXPCCoding>

@property (readonly, nonatomic) double duration;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)cancelAfterInterval:(double)interval;
+ (id)warnAfterInterval:(double)interval;
+ (id)timeoutAfterInterval:(double)interval;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithDuration:(double)duration;
- (_Bool)canBePaused;
- (_Bool)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* BLSDurationAttribute_h */
