//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSDiagnosticFlipbookFrameSurfaceProvider_Protocol_h
#define BLSDiagnosticFlipbookFrameSurfaceProvider_Protocol_h
@import Foundation;



@protocol BLSDiagnosticFlipbookFrameSurfaceProvider <NSObject>

@required

/* required instance methods */
- (struct __IOSurface *)surfaceForFrame:(id)frame;
- (struct __IOSurface *)rawSurfaceForFrame:(id)frame;

@optional

@end

#endif /* BLSDiagnosticFlipbookFrameSurfaceProvider_Protocol_h */
