//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSDiagnosticFlipbookFrame_h
#define BLSDiagnosticFlipbookFrame_h
@import Foundation;

#include "BLSDiagnosticFlipbookFrameSurfaceProvider-Protocol.h"
#include "BLSDiagnosticPresentationDateSpecifier.h"
#include "BLSPresentationDateSpecifying-Protocol.h"
#include "BLSRenderedFlipbookFrame-Protocol.h"



@class NSObject, NSString, NSUUID;

@interface BLSDiagnosticFlipbookFrame : NSObject <BLSRenderedFlipbookFrame, NSSecureCoding, BSXPCCoding> {
    /* instance variables */
    BLSDiagnosticPresentationDateSpecifier *_specifier;
}

@property (weak) id <BLSDiagnosticFlipbookFrameSurfaceProvider> surfaceProvider;
@property (readonly, nonatomic) NSUUID *uuid;
@property (readonly, nonatomic) unsigned long long presentationTime;
@property (readonly, nonatomic) unsigned long long frameId;
@property (readonly, nonatomic) float apl;
@property (readonly, nonatomic) float aplDimming;
@property (readonly, nonatomic) unsigned long long memoryUsage;
@property (readonly, nonatomic) id <BLSPresentationDateSpecifying> bls_specifier;
@property (readonly, nonatomic) struct __IOSurface * surface;
@property (readonly, nonatomic) struct __IOSurface * rawSurface;
@property (readonly, nonatomic) CGRect rawSurfaceFrame;
@property (readonly, nonatomic) _Bool inverted;
@property (readonly, nonatomic) NSUUID *bls_uuid;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)createWithFrame:(id)frame;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithFrame:(id)frame;
- (id)initWithPresentationTime:(unsigned long long)time frameId:(unsigned long long)id apl:(float)apl aplDimming:(float)dimming memoryUsage:(unsigned long long)usage rawSurfaceFrameRect:(CGRect)rect inverted:(_Bool)inverted specifier:(id)specifier uuid:(id)uuid;
- (id)bls_loggingString;
- (id)bls_shortLoggingString;
- (_Bool)isEqual:(id)equal;
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isInverted;

@end

#endif /* BLSDiagnosticFlipbookFrame_h */
