//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSDiagnosticEnvironmentDateSpecifier_h
#define BLSDiagnosticEnvironmentDateSpecifier_h
@import Foundation;

#include "BLSAlwaysOnDateSpecifier.h"
#include "BLSEnvironmentDateSpecifying-Protocol.h"
#include "BSXPCCoding-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSObject, NSString;

@interface BLSDiagnosticEnvironmentDateSpecifier : NSObject <BLSEnvironmentDateSpecifying, NSSecureCoding, BSXPCCoding>

@property (readonly, nonatomic) BLSAlwaysOnDateSpecifier *dateSpecifier;
@property (readonly, copy, nonatomic) NSString *environmentIdentifier;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)createWithSpecifier:(id)specifier;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithDateSpecifier:(id)specifier environmentIdentifier:(id)identifier;
- (id)bls_loggingString;
- (id)bls_shortLoggingString;
- (_Bool)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* BLSDiagnosticEnvironmentDateSpecifier_h */
