//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSEnvironmentDateSpecifying_Protocol_h
#define BLSEnvironmentDateSpecifying_Protocol_h
@import Foundation;

#include "BLSAlwaysOnDateSpecifier.h"


@class NSString;

@protocol BLSEnvironmentDateSpecifying <NSObject>

@required

@property (readonly, nonatomic) BLSAlwaysOnDateSpecifier *dateSpecifier;
@property (readonly, copy, nonatomic) NSString *environmentIdentifier;

/* required instance methods */
- (id)bls_loggingString;
- (id)bls_shortLoggingString;

@optional

@end

#endif /* BLSEnvironmentDateSpecifying_Protocol_h */
