//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSFrameSpecifiersRequest_h
#define BLSFrameSpecifiersRequest_h
@import Foundation;

@class NSDate, NSDateInterval, NSObject;

@interface BLSFrameSpecifiersRequest : NSObject {
    /* instance variables */
    id /* block */ _completion;
    os_unfair_lock _lock;
    _Bool _lock_completed;
}

@property (readonly, nonatomic) NSDateInterval *dateInterval;
@property (readonly, nonatomic) NSDate *previousPresentationDate;
@property (readonly, nonatomic) _Bool shouldReset;

/* instance methods */
- (id)initWithDateInterval:(id)interval previousPresentationDate:(id)date shouldReset:(_Bool)reset completion:(id /* block */)completion;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (void)completeWithDateSpecifiers:(id)specifiers;

@end

#endif /* BLSFrameSpecifiersRequest_h */
