//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSFrameSpecifiersRequestAction_h
#define BLSFrameSpecifiersRequestAction_h
@import Foundation;

@class BSAction, NSDate, NSDateInterval;

@interface BLSFrameSpecifiersRequestAction : BSAction

@property (readonly, nonatomic) NSDateInterval *dateInterval;
@property (readonly, nonatomic) NSDate *previousPresentationDate;
@property (readonly, nonatomic) _Bool shouldReset;

/* instance methods */
- (id)initWithDateInterval:(id)interval previousPresentationDate:(id)date shouldReset:(_Bool)reset completion:(id /* block */)completion;

@end

#endif /* BLSFrameSpecifiersRequestAction_h */
