//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSInvalidOnSystemSleepAttribute_h
#define BLSInvalidOnSystemSleepAttribute_h
@import Foundation;

#include "BLSAttribute.h"

@interface BLSInvalidOnSystemSleepAttribute : BLSAttribute

/* class methods */
+ (id)invalidateOnSystemSleep;

/* instance methods */
- (_Bool)canBePaused;

@end

#endif /* BLSInvalidOnSystemSleepAttribute_h */
