//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSPendingBacklightProxy_h
#define BLSPendingBacklightProxy_h
@import Foundation;

#include "BLSBacklightProxy-Protocol.h"

@class NSHashTable, NSMutableArray, NSObject, NSString;

@interface BLSPendingBacklightProxy : NSObject <BLSBacklightProxy> {
    /* instance variables */
    NSMutableArray *_requests;
    NSHashTable *_observers;
    id <BLSBacklightProxy> _replacementBacklightProxy;
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
}

@property (readonly, nonatomic) long long backlightState;
@property (readonly, nonatomic) long long flipbookState;
@property (readonly, nonatomic) _Bool transitioning;
@property (readonly, nonatomic) _Bool alwaysOnEnabled;
@property (readonly, nonatomic) _Bool deviceSupportsAlwaysOn;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (_Bool)isTransitioning;
- (_Bool)isAlwaysOnEnabled;
- (void)addObserver:(id)observer;
- (void)removeObserver:(id)observer;
- (id)performChangeRequest:(id)request;
- (void)replaceWithBacklightProxy:(id)proxy;

@end

#endif /* BLSPendingBacklightProxy_h */
