//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSPendingAssertionService_h
#define BLSPendingAssertionService_h
@import Foundation;

#include "BLSAssertionService-Protocol.h"

@class NSMutableArray, NSObject, NSString;

@interface BLSPendingAssertionService : NSObject <BLSAssertionService> {
    /* instance variables */
    NSMutableArray *_assertionsToAcquire;
    id <BLSAssertionService> _replacementService;
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (oneway void)acquireAssertion:(id)assertion;
- (oneway void)cancelAssertion:(id)assertion withError:(id)error;
- (oneway void)restartAssertionTimeoutTimer:(id)timer;
- (void)replaceWithService:(id)service;

@end

#endif /* BLSPendingAssertionService_h */
