//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSRenderedFlipbookFrame_Protocol_h
#define BLSRenderedFlipbookFrame_Protocol_h
@import Foundation;

#include "BLSPresentationDateSpecifying-Protocol.h"
#include "NSObject-Protocol.h"

@class NSUUID;

@protocol BLSRenderedFlipbookFrame <NSObject>

@required

@property (readonly, nonatomic) unsigned long long presentationTime;
@property (readonly, nonatomic) unsigned long long frameId;
@property (readonly, nonatomic) float apl;
@property (readonly, nonatomic) float aplDimming;
@property (readonly, nonatomic) unsigned long long memoryUsage;
@property (readonly, nonatomic) id <BLSPresentationDateSpecifying> bls_specifier;
@property (readonly, nonatomic) struct __IOSurface * surface;
@property (readonly, nonatomic) struct __IOSurface * rawSurface;
@property (readonly, nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } rawSurfaceFrame;
@property (readonly, nonatomic) _Bool inverted;
@property (readonly, nonatomic) NSUUID *bls_uuid;

/* required instance methods */
- (id)bls_loggingString;
- (id)bls_shortLoggingString;
- (_Bool)isInverted;

@optional

@end

#endif /* BLSRenderedFlipbookFrame_Protocol_h */
