//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSXPCBacklightProxy_h
#define BLSXPCBacklightProxy_h
@import Foundation;

#include "BLSBacklightProxy-Protocol.h"
#include "BLSXPCBacklightProxyClientInterface-Protocol.h"
#include "BSInvalidatable-Protocol.h"

@class BSServiceConnection, NSMapTable, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface BLSXPCBacklightProxy : NSObject <BLSBacklightProxy, BLSXPCBacklightProxyClientInterface, BSInvalidatable> {
    /* instance variables */
    NSMapTable *_lock_observers;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    BSServiceConnection *_connection;
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
    int _lock_observingDidCompleteUpdateToStateCount;
    int _lock_observingEventsArrayCount;
    int _lock_observingDidChangeAlwaysOnEnabledCount;
    int _lock_observingActivatingWithEventCount;
    int _lock_observingDeactivatingWithEventCount;
    int _lock_observingPerformingEventCount;
    long long _lock_backlightState;
    _Bool _lock_isBacklightStateCached;
    _Bool _lock_isAlwaysOnEnabled;
    _Bool _lock_isAlwaysOnEnabledCached;
    _Bool _lock_deviceSupportsAlwaysOn;
    _Bool _lock_deviceSupportsAlwaysOnCached;
    _Bool _lock_invalidated;
}

@property (readonly, nonatomic) long long backlightState;
@property (readonly, nonatomic) long long flipbookState;
@property (readonly, nonatomic) _Bool transitioning;
@property (readonly, nonatomic) _Bool alwaysOnEnabled;
@property (readonly, nonatomic) _Bool deviceSupportsAlwaysOn;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (void)invalidate;
- (void)dealloc;
- (_Bool)isTransitioning;
- (_Bool)isAlwaysOnEnabled;
- (void)addObserver:(id)observer;
- (void)removeObserver:(id)observer;
- (id)performChangeRequest:(id)request;
- (oneway void)didCompleteUpdateToState:(id)state forEvents:(id)events abortedEvents:(id)events;
- (oneway void)didChangeAlwaysOnEnabled:(id)enabled;
- (oneway void)performingEvent:(id)event;

@end

#endif /* BLSXPCBacklightProxy_h */
