//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSXPCBacklightProxyObserverMask_h
#define BLSXPCBacklightProxyObserverMask_h
@import Foundation;





@class NSObject, NSString;

@interface BLSXPCBacklightProxyObserverMask : NSObject <NSCopying, NSSecureCoding, BSXPCCoding>

@property (readonly, nonatomic) _Bool observingDidCompleteUpdateToState;
@property (readonly, nonatomic) _Bool observingEventsArray;
@property (readonly, nonatomic) _Bool observingDidChangeAlwaysOnEnabled;
@property (readonly, nonatomic) _Bool observingActivatingWithEvent;
@property (readonly, nonatomic) _Bool observingDeactivatingWithEvent;
@property (readonly, nonatomic) _Bool observingPerformingEvent;
@property (readonly, nonatomic) _Bool observing;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)maskForObserver:(id)observer;
+ (id)maskForObservingDidCompleteUpdateToState:(_Bool)state observingEventsArray:(_Bool)array didChangeAlwaysOnEnabled:(_Bool)enabled activatingWithEvent:(_Bool)event deactivatingWithEvent:(_Bool)event performingEvent:(_Bool)event;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithObservingDidCompleteUpdateToState:(_Bool)state observingEventsArray:(_Bool)array didChangeAlwaysOnEnabled:(_Bool)enabled activatingWithEvent:(_Bool)event deactivatingWithEvent:(_Bool)event performingEvent:(_Bool)event;
- (id)initWithObserver:(id)observer;
- (_Bool)isObserving;
- (_Bool)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isObservingDidCompleteUpdateToState;
- (_Bool)isObservingEventsArray;
- (_Bool)isObservingDidChangeAlwaysOnEnabled;
- (_Bool)isObservingActivatingWithEvent;
- (_Bool)isObservingDeactivatingWithEvent;
- (_Bool)isObservingPerformingEvent;

@end

#endif /* BLSXPCBacklightProxyObserverMask_h */
