//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSXPCAssertionService_h
#define BLSXPCAssertionService_h
@import Foundation;

#include "BLSAssertionService-Protocol.h"
#include "BLSXPCAssertionServiceClientInterface-Protocol.h"


@class BSServiceConnection, NSMapTable, NSMutableSet, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface BLSXPCAssertionService : NSObject <BLSAssertionService, BLSXPCAssertionServiceClientInterface, BSInvalidatable> {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_requestQueue;
    BSServiceConnection *_connection;
    NSMapTable *_queue_assertions;
    NSMutableSet *_queue_assertionsToReacquire;
    os_unfair_lock _lock;
    _Bool _lock_invalidated;
}

@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)defaultEndpoint;

/* instance methods */
- (id)init;
- (id)initWithEndpoint:(id)endpoint;
- (void)invalidate;
- (void)dealloc;
- (oneway void)acquireAssertion:(id)assertion;
- (oneway void)cancelAssertion:(id)assertion withError:(id)error;
- (oneway void)restartAssertionTimeoutTimer:(id)timer;
- (void)replaceWithService:(id)service;
- (oneway void)assertion:(id)assertion failedToAcquireWithError:(id)error;
- (oneway void)assertionAcquired:(id)acquired;
- (oneway void)assertionWillCancel:(id)cancel;
- (oneway void)assertionDidCancel:(id)cancel withError:(id)error;
- (oneway void)assertionPaused:(id)paused;
- (oneway void)assertionResumed:(id)resumed;

@end

#endif /* BLSXPCAssertionService_h */
