//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BSInvalidatable_Protocol_h
#define BSInvalidatable_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol BSInvalidatable <NSObject>

@required

/* required instance methods */
- (void)invalidate;

@optional

@end

#endif /* BSInvalidatable_Protocol_h */
