//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef NSCoding_Protocol_h
#define NSCoding_Protocol_h
@import Foundation;

@protocol NSCoding

@required

/* required instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;

@optional

@end

#endif /* NSCoding_Protocol_h */
