//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef NSMutableCopying_Protocol_h
#define NSMutableCopying_Protocol_h
@import Foundation;

@protocol NSMutableCopying

@required

/* required instance methods */
- (id)mutableCopyWithZone:(struct _NSZone *)zone;

@optional

@end

#endif /* NSMutableCopying_Protocol_h */
