//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef NSObject_Protocol_h
#define NSObject_Protocol_h
@import Foundation;

@class NSString;

@protocol NSObject

@required

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;

/* required instance methods */
- (_Bool)isEqual:(id)equal;
- (Class)class;
- (id)self;
- (id)performSelector:(SEL)selector;
- (id)performSelector:(SEL)selector withObject:(id)object;
- (id)performSelector:(SEL)selector withObject:(id)object withObject:(id)object;
- (_Bool)isProxy;
- (_Bool)isKindOfClass:(Class)_class;
- (_Bool)isMemberOfClass:(Class)_class;
- (_Bool)conformsToProtocol:(id)protocol;
- (_Bool)respondsToSelector:(SEL)selector;
- (id)retain;
- (oneway void)release;
- (id)autorelease;
- (unsigned long long)retainCount;
- (struct _NSZone *)zone;

@optional

@property (readonly, copy) NSString *debugDescription;

@end

#endif /* NSObject_Protocol_h */
