//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef FBSMutableSceneSettings_BacklightServicesInternal_h
#define FBSMutableSceneSettings_BacklightServicesInternal_h
@import Foundation;

@interface FBSMutableSceneSettings (BacklightServicesInternal) <BLSBacklightSceneSettings>

/* instance methods */
- (void)bls_setDelegateActive:(_Bool)active;
- (void)bls_setVisualState:(id)state;
- (void)bls_setPresentationDate:(id)date;
- (void)bls_setAlwaysOnEnabledForEnvironment:(_Bool)environment;
- (void)bls_setRenderSeed:(unsigned long long)seed;
- (void)bls_setLiveUpdating:(_Bool)updating;
- (void)bls_setUnrestrictedFramerateUpdates:(_Bool)updates;

@end

#endif /* FBSMutableSceneSettings_BacklightServicesInternal_h */
