//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef FBSSceneClientSettings_BacklightServices_h
#define FBSSceneClientSettings_BacklightServices_h
@import Foundation;

@interface FBSSceneClientSettings (BacklightServices) <BLSBacklightSceneClientSettings>

/* instance methods */
- (_Bool)bls_hasDelegate;
- (_Bool)bls_supportsAlwaysOn;
- (_Bool)bls_optsOutOfProcessAssertions;

@end

#endif /* FBSSceneClientSettings_BacklightServices_h */
