//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef FBSScene_BacklightServices_h
#define FBSScene_BacklightServices_h
@import Foundation;

@interface FBSScene (BacklightServices)

/* instance methods */
- (id)backlightSceneEnvironmentWithCreationBlock:(id /* block */)block;
- (id)backlightSceneEnvironment;

@end

#endif /* FBSScene_BacklightServices_h */
