//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLS1HzFlipbookAttribute_h
#define BLS1HzFlipbookAttribute_h
@import Foundation;

#include "BLSSceneAttribute.h"

@interface BLS1HzFlipbookAttribute : BLSSceneAttribute

/* class methods */
+ (id)set1HzFlipbookForFBSScene:(id)fbsscene;
+ (id)set1HzFlipbooForFBSSceneIdentityToken:(id)token;
+ (id)set1HzFlipbook;

/* instance methods */
- (_Bool)checkEntitlementSourceForRequiredEntitlements:(id)entitlements error:(out id *)error;

@end

#endif /* BLS1HzFlipbookAttribute_h */
