//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAssertionDescriptor_h
#define BLSAssertionDescriptor_h
@import Foundation;





@class NSArray, NSObject, NSString;

@interface BLSAssertionDescriptor : NSObject <NSCopying, NSSecureCoding, BSXPCCoding>

@property (readonly, copy, nonatomic) NSString *explanation;
@property (readonly, copy, nonatomic) NSArray *attributes;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithExplanation:(id)explanation attributes:(id)attributes;
- (id)attributeOfClass:(Class)_class;
- (id)attributesOfClasses:(id)classes;
- (_Bool)checkEntitlementSourceForRequiredEntitlements:(id)entitlements error:(out id *)error;
- (_Bool)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* BLSAssertionDescriptor_h */
