//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAlwaysOnPeriodicTimeline_h
#define BLSAlwaysOnPeriodicTimeline_h
@import Foundation;

#include "BLSAlwaysOnTimeline.h"

@class NSDate;

@interface BLSAlwaysOnPeriodicTimeline : BLSAlwaysOnTimeline {
    /* instance variables */
    double _periodicInterval;
    NSDate *_periodicStart;
}

/* instance methods */
- (id)initWithUpdateInterval:(double)interval startDate:(id)date identifier:(id)identifier configure:(id /* block */)configure;
- (id)description;
- (long long)requestedFidelityForStartEntryInDateInterval:(id)interval withPreviousEntry:(id)entry;
- (id)unconfiguredEntriesForDateInterval:(id)interval previousEntry:(id)entry;

@end

#endif /* BLSAlwaysOnPeriodicTimeline_h */
