//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAssertionService_Protocol_h
#define BLSAssertionService_Protocol_h
@import Foundation;



@protocol BLSAssertionService <NSObject>

@required

/* required instance methods */
- (oneway void)acquireAssertion:(id)assertion;
- (oneway void)cancelAssertion:(id)assertion withError:(id)error;
- (oneway void)restartAssertionTimeoutTimer:(id)timer;
- (void)replaceWithService:(id)service;

@optional

@end

#endif /* BLSAssertionService_Protocol_h */
