//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklight_h
#define BLSBacklight_h
@import Foundation;

#include "BLSBacklightChangeRequestable-Protocol.h"
#include "BLSBacklightProxy-Protocol.h"
#include "BLSBacklightStateObservable-Protocol.h"

@class NSObject, NSString;

@interface BLSBacklight : NSObject <BLSBacklightStateObservable, BLSBacklightChangeRequestable> {
    /* instance variables */
    id <BLSBacklightProxy> _backlightProxy;
}

@property (readonly, nonatomic) long long backlightState;
@property (readonly, nonatomic) long long flipbookState;
@property (readonly, nonatomic) _Bool transitioning;
@property (readonly, nonatomic) _Bool alwaysOnEnabled;
@property (readonly, nonatomic) _Bool deviceSupportsAlwaysOn;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)sharedBacklight;
+ (void)setDefaultBacklightProxy:(id)proxy;

/* instance methods */
- (id)init;
- (_Bool)isTransitioning;
- (_Bool)isAlwaysOnEnabled;
- (id)performChangeRequest:(id)request;
- (void)addObserver:(id)observer;
- (void)removeObserver:(id)observer;

@end

#endif /* BLSBacklight_h */
