//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightSceneSettings_Protocol_h
#define BLSBacklightSceneSettings_Protocol_h
@import Foundation;

#include "BLSBacklightSceneVisualState.h"


@class NSDate;

@protocol BLSBacklightSceneSettings <NSObject>

@required

@property (readonly, nonatomic) _Bool bls_delegateActive;
@property (readonly, nonatomic) BLSBacklightSceneVisualState *bls_visualState;
@property (readonly, nonatomic) NSDate *bls_presentationDate;
@property (readonly, nonatomic) _Bool bls_alwaysOnEnabledForEnvironment;
@property (readonly, nonatomic) unsigned long long bls_renderSeed;
@property (readonly, nonatomic) _Bool bls_liveUpdating;
@property (readonly, nonatomic) _Bool bls_unrestrictedFramerateUpdates;

/* required instance methods */
- (_Bool)bls_isDelegateActive;
- (_Bool)bls_isAlwaysOnEnabledForEnvironment;
- (_Bool)bls_isLiveUpdating;
- (_Bool)bls_hasUnrestrictedFramerateUpdates;

@optional

@end

#endif /* BLSBacklightSceneSettings_Protocol_h */
