//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightSceneClientSettings_Protocol_h
#define BLSBacklightSceneClientSettings_Protocol_h
@import Foundation;



@protocol BLSBacklightSceneClientSettings <NSObject>

@required

@property (readonly, nonatomic) _Bool bls_hasDelegate;
@property (readonly, nonatomic) _Bool bls_supportsAlwaysOn;
@property (readonly, nonatomic) _Bool bls_optsOutOfProcessAssertions;

@optional

@end

#endif /* BLSBacklightSceneClientSettings_Protocol_h */
