//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightSceneUpdateAction_h
#define BLSBacklightSceneUpdateAction_h
@import Foundation;

#include "BLSBacklightChangeEvent.h"

@class BSAction;

@interface BLSBacklightSceneUpdateAction : BSAction

@property (readonly, nonatomic) BLSBacklightChangeEvent *event;
@property (readonly, nonatomic) _Bool animated;
@property (readonly, nonatomic) _Bool touchTargetable;
@property (readonly, nonatomic) _Bool isUpdateToDateSpecifier;

/* instance methods */
- (id)initWithBacklightChangeEvent:(id)event animated:(_Bool)animated touchTargetable:(_Bool)targetable isUpdateToDateSpecifier:(_Bool)specifier completion:(id /* block */)completion;
- (_Bool)isAnimated;
- (_Bool)isTouchTargetable;

@end

#endif /* BLSBacklightSceneUpdateAction_h */
