//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightChangeRequest_h
#define BLSBacklightChangeRequest_h
@import Foundation;

#include "BLSBacklightChangeSourceEventMetadata.h"




@class NSObject, NSString;

@interface BLSBacklightChangeRequest : NSObject <BSXPCCoding, NSCopying, NSSecureCoding>

@property (readonly, nonatomic) long long requestedActivityState;
@property (readonly, copy, nonatomic) NSString *explanation;
@property (readonly, nonatomic) unsigned long long timestamp;
@property (readonly, nonatomic) long long sourceEvent;
@property (readonly, nonatomic) BLSBacklightChangeSourceEventMetadata *sourceEventMetadata;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithRequestedActivityState:(long long)state explanation:(id)explanation timestamp:(unsigned long long)timestamp sourceEvent:(long long)event sourceEventMetadata:(id)metadata;
- (_Bool)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* BLSBacklightChangeRequest_h */
