//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightSceneUpdateContext_h
#define BLSBacklightSceneUpdateContext_h
@import Foundation;

#include "BLSAlwaysOnFrameSpecifier.h"
#include "BLSBacklightChangeEvent.h"
#include "BLSBacklightSceneVisualState.h"

@class NSObject;

@interface BLSBacklightSceneUpdateContext : NSObject

@property (readonly, nonatomic) BLSBacklightSceneVisualState *visualState;
@property (readonly, nonatomic) BLSBacklightSceneVisualState *previousVisualState;
@property (readonly, nonatomic) BLSAlwaysOnFrameSpecifier *frameSpecifier;
@property (readonly, nonatomic) _Bool animated;
@property (readonly, nonatomic) BLSBacklightChangeEvent *triggerEvent;
@property (readonly, nonatomic) _Bool touchTargetable;

/* instance methods */
- (id)initWithVisualState:(id)state previousVisualState:(id)state frameSpecifier:(id)specifier animated:(_Bool)animated triggerEvent:(id)event touchTargetable:(_Bool)targetable;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (_Bool)isAnimated;
- (_Bool)isTouchTargetable;

@end

#endif /* BLSBacklightSceneUpdateContext_h */
