//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightSceneSettingsDiffInspector_h
#define BLSBacklightSceneSettingsDiffInspector_h
@import Foundation;

@class FBSSceneSettingsDiffInspector;

@interface BLSBacklightSceneSettingsDiffInspector : FBSSceneSettingsDiffInspector

/* instance methods */
- (id)init;
- (struct { unsigned int x0:1; unsigned int x1:1; unsigned int x2:1; unsigned int x3:1; unsigned int x4:1; })inspectDiff:(id)diff;

@end

#endif /* BLSBacklightSceneSettingsDiffInspector_h */
