//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightFBSSceneEnvironmentActionHandler_h
#define BLSBacklightFBSSceneEnvironmentActionHandler_h
@import Foundation;

@class NSObject;

@interface BLSBacklightFBSSceneEnvironmentActionHandler : NSObject

/* class methods */
+ (id)desiredFidelityRequestFromAction:(id)action;
+ (id)frameSpecifiersRequestFromAction:(id)action;

/* instance methods */
- (id)respondToActions:(id)actions forFBSScene:(id)fbsscene fromTransitionContext:(id)context;

@end

#endif /* BLSBacklightFBSSceneEnvironmentActionHandler_h */
