//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSCacheFlipbookOnDisplayWakeAttribute_h
#define BLSCacheFlipbookOnDisplayWakeAttribute_h
@import Foundation;

#include "BLSSceneAttribute.h"

@interface BLSCacheFlipbookOnDisplayWakeAttribute : BLSSceneAttribute

/* class methods */
+ (id)cacheFlipbookForFBSScene:(id)fbsscene;
+ (id)cacheFlipbookForFBSSceneIdentityToken:(id)token;
+ (id)cacheFlipbook;

/* instance methods */
- (_Bool)checkEntitlementSourceForRequiredEntitlements:(id)entitlements error:(out id *)error;

@end

#endif /* BLSCacheFlipbookOnDisplayWakeAttribute_h */
