//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSDiagnosticPresentationDateSpecifier_h
#define BLSDiagnosticPresentationDateSpecifier_h
@import Foundation;

#include "BLSPresentationDateSpecifying-Protocol.h"



@class NSArray, NSDate, NSObject, NSString;

@interface BLSDiagnosticPresentationDateSpecifier : NSObject <BLSPresentationDateSpecifying, NSSecureCoding, BSXPCCoding>

@property (readonly, nonatomic) NSDate *presentationDate;
@property (readonly, nonatomic) NSArray *specifiers;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)createWithSpecifier:(id)specifier;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithPresentationDate:(id)date specifiers:(id)specifiers;
- (id)bls_loggingString;
- (id)bls_shortLoggingString;
- (_Bool)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* BLSDiagnosticPresentationDateSpecifier_h */
