//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSFlipbookDiagnosticsProviding_Protocol_h
#define BLSFlipbookDiagnosticsProviding_Protocol_h
@import Foundation;



@protocol BLSFlipbookDiagnosticsProviding <NSObject>

@required

/* required instance methods */
- (id)allFlipbookFrames;
- (id)frameWithUUID:(id)uuid;
- (id)frameOnGlassNow;
- (id)frameOnGlassWhenFlipbookLastCancelled;

@optional

@end

#endif /* BLSFlipbookDiagnosticsProviding_Protocol_h */
