//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSGlobalHighLuminanceAlwaysOnAttribute_h
#define BLSGlobalHighLuminanceAlwaysOnAttribute_h
@import Foundation;

#include "BLSAttribute.h"

@interface BLSGlobalHighLuminanceAlwaysOnAttribute : BLSAttribute

/* instance methods */
- (_Bool)checkEntitlementSourceForRequiredEntitlements:(id)entitlements error:(out id *)error;

@end

#endif /* BLSGlobalHighLuminanceAlwaysOnAttribute_h */
