//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSPeekingEnumerator_h
#define BLSPeekingEnumerator_h
@import Foundation;

@class NSEnumerator;

@interface BLSPeekingEnumerator : NSEnumerator {
    /* instance variables */
    NSEnumerator *_enumerator;
    id _peekedObject;
}

/* class methods */
+ (id)peekingEnumeratorWithEnumerator:(id)enumerator;

/* instance methods */
- (id)nextObject;
- (id)peekNextObject;

@end

#endif /* BLSPeekingEnumerator_h */
