//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSRequestLiveUpdatingAttribute_h
#define BLSRequestLiveUpdatingAttribute_h
@import Foundation;

#include "BLSSceneAttribute.h"

@interface BLSRequestLiveUpdatingAttribute : BLSSceneAttribute

/* class methods */
+ (id)requestLiveUpdatingForFBSScene:(id)fbsscene;
+ (id)requestLiveUpdatingForFBSSceneIdentityToken:(id)token;

/* instance methods */
- (_Bool)checkEntitlementSourceForRequiredEntitlements:(id)entitlements error:(out id *)error;

@end

#endif /* BLSRequestLiveUpdatingAttribute_h */
