//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSSharedWorkloop_h
#define BLSSharedWorkloop_h
@import Foundation;

@class NSObject;

@interface BLSSharedWorkloop : NSObject

/* class methods */
+ (id)workloop;
+ (void)dispatchWithQOSClass:(unsigned int)qosclass block:(id /* block */)block;
+ (id)serialQueueWithQOSClass:(unsigned int)qosclass label:(const char *)label;

@end

#endif /* BLSSharedWorkloop_h */
