//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSSceneAttribute_h
#define BLSSceneAttribute_h
@import Foundation;

#include "BLSAttribute.h"


@class FBSSceneIdentityToken, NSString;

@interface BLSSceneAttribute : BLSAttribute <BSXPCCoding>

@property (readonly, nonatomic) FBSSceneIdentityToken *sceneIdentityToken;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithFBSScene:(id)fbsscene;
- (id)initWithSceneIdentityToken:(id)token;
- (_Bool)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* BLSSceneAttribute_h */
