//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSXPCBacklightProxyHostInterface_Protocol_h
#define BLSXPCBacklightProxyHostInterface_Protocol_h
@import Foundation;



@protocol BLSXPCBacklightProxyHostInterface <NSObject>

@required

/* required instance methods */
- (id)getBacklightState;
- (id)getFlipbookState;
- (_Bool)isTransitioning;
- (_Bool)isAlwaysOnEnabled;
- (_Bool)deviceSupportsAlwaysOn;
- (id)performChangeRequest:(id)request;
- (oneway void)nowObservingWithMask:(id)mask completion:(id /* block */)completion;

@optional

@end

#endif /* BLSXPCBacklightProxyHostInterface_Protocol_h */
