//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSXPCBacklightProxyClientInterface_Protocol_h
#define BLSXPCBacklightProxyClientInterface_Protocol_h
@import Foundation;



@protocol BLSXPCBacklightProxyClientInterface <NSObject>

@required

/* required instance methods */
- (oneway void)didCompleteUpdateToState:(id)state forEvents:(id)events abortedEvents:(id)events;
- (oneway void)didChangeAlwaysOnEnabled:(id)enabled;
- (oneway void)performingEvent:(id)event;

@optional

@end

#endif /* BLSXPCBacklightProxyClientInterface_Protocol_h */
