//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSXPCAssertionServiceClientInterface_Protocol_h
#define BLSXPCAssertionServiceClientInterface_Protocol_h
@import Foundation;



@protocol BLSXPCAssertionServiceClientInterface <NSObject>

@required

/* required instance methods */
- (oneway void)assertionAcquired:(id)acquired;
- (oneway void)assertion:(id)assertion failedToAcquireWithError:(id)error;
- (oneway void)assertionPaused:(id)paused;
- (oneway void)assertionResumed:(id)resumed;
- (oneway void)assertionWillCancel:(id)cancel;
- (oneway void)assertionDidCancel:(id)cancel withError:(id)error;

@optional

@end

#endif /* BLSXPCAssertionServiceClientInterface_Protocol_h */
