//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BSDescriptionStream_BacklightServices_h
#define BSDescriptionStream_BacklightServices_h
@import Foundation;

@interface BSDescriptionStream (BacklightServices)

/* instance methods */
- (void)bls_appendBoundedCollection:(id)collection withName:(id)name maximumItems:(long long)items itemBlock:(id /* block */)block;
- (id)bls_appendTimeInterval:(double)interval withName:(id)name decomposeUnits:(_Bool)units;

@end

#endif /* BSDescriptionStream_BacklightServices_h */
