//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef NSArray_BacklightServices_h
#define NSArray_BacklightServices_h
@import Foundation;

@interface NSArray (BacklightServices)

/* instance methods */
- (id)bls_boundedDescription;
- (id)bls_boundedDescriptionWithTransformer:(id /* block */)transformer;
- (id)bls_boundedDescriptionWithMax:(long long)max;
- (id)bls_boundedDescriptionWithMax:(long long)max transformer:(id /* block */)transformer;

@end

#endif /* NSArray_BacklightServices_h */
