//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAssertionObserving_Protocol_h
#define BLSAssertionObserving_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol BLSAssertionObserving <NSObject>

@required

@optional

/* optional instance methods */
- (void)assertionWasAcquired:(id)acquired;
- (void)assertion:(id)assertion didFailToAcquireWithError:(id)error;
- (void)assertionDidPause:(id)pause;
- (void)assertionDidResume:(id)resume;
- (void)assertionWillCancel:(id)cancel;
- (void)assertion:(id)assertion didCancelWithError:(id)error;

@end

#endif /* BLSAssertionObserving_Protocol_h */
