//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAlwaysOnFrameSpecifier_h
#define BLSAlwaysOnFrameSpecifier_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSArray, NSDateInterval, NSObject;

@interface BLSAlwaysOnFrameSpecifier : NSObject <NSCopying> {
    /* instance variables */
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
}

@property long long grantedFidelity;
@property (readonly) NSArray *entrySpecifiers;
@property (readonly) NSDateInterval *presentationInterval;
@property (readonly) long long requestedFidelity;

/* class methods */
+ (id)loggingStringForPresentationInterval:(id)interval;
+ (id)shortLoggingStringForPresentationInterval:(id)interval;

/* instance methods */
- (id)initWithTimelineEntrySpecifiers:(id)specifiers presentationInterval:(id)interval;
- (id)entrySpecifierForTimelineIdentifier:(id)identifier;
- (long long)compare:(id)compare;
- (id)correctedSpecifierWithNextSpecifier:(id)specifier;
- (id)description;
- (id)debugDescription;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* BLSAlwaysOnFrameSpecifier_h */
