//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAssertionServiceResponding_Protocol_h
#define BLSAssertionServiceResponding_Protocol_h
@import Foundation;

#include "BLSAsserting-Protocol.h"

@protocol BLSAssertionServiceResponding <BLSAsserting>

@required

/* required instance methods */
- (oneway void)serviceDidAcquire;
- (oneway void)serviceFailedToAcquireWithError:(id)error;
- (oneway void)serviceDidPause;
- (oneway void)serviceDidResume;
- (oneway void)serviceWillCancel;
- (oneway void)serviceDidCancelWithError:(id)error;

@optional

@end

#endif /* BLSAssertionServiceResponding_Protocol_h */
