//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAsserting_Protocol_h
#define BLSAsserting_Protocol_h
@import Foundation;

#include "BLSAssertionDescriptor.h"
#include "BLSAssertionIdentifier.h"
#include "NSObject-Protocol.h"

@protocol BLSAsserting <NSObject>

@required

@property (readonly, nonatomic) _Bool acquired;
@property (readonly, nonatomic) BLSAssertionDescriptor *descriptor;
@property (retain, nonatomic) BLSAssertionIdentifier *identifier;
@property (readonly, nonatomic) unsigned long long acquisitionState;
@property (readonly, nonatomic) double activeDuration;

/* required instance methods */
- (_Bool)isAcquired;

@optional

@end

#endif /* BLSAsserting_Protocol_h */
