//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSAlwaysOnTimelineEntrySpecifier_h
#define BLSAlwaysOnTimelineEntrySpecifier_h
@import Foundation;

#include "BLSAlwaysOnTimelineEntry.h"
#include "NSCopying-Protocol.h"

@class NSObject;

@interface BLSAlwaysOnTimelineEntrySpecifier : NSObject <NSCopying> {
    /* instance variables */
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
}

@property _Bool didChange;
@property long long grantedFidelity;
@property long long requestedFidelity;
@property (readonly) BLSAlwaysOnTimelineEntry *timelineEntry;
@property (readonly) double percentComplete;
@property (readonly) BLSAlwaysOnTimelineEntry *previousTimelineEntry;

/* instance methods */
- (id)initWithTimelineEntry:(id)entry percentComplete:(double)complete previousTimelineEntry:(id)entry didChange:(_Bool)change;
- (long long)compare:(id)compare;
- (id)description;
- (void)appendFidelityToTarget:(id)target;
- (id)debugDescription;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* BLSAlwaysOnTimelineEntrySpecifier_h */
