//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightChangeSourceEventDisplayTapMetadata_h
#define BLSBacklightChangeSourceEventDisplayTapMetadata_h
@import Foundation;

#include "BLSBacklightChangeSourceEventMetadata.h"

@interface BLSBacklightChangeSourceEventDisplayTapMetadata : BLSBacklightChangeSourceEventMetadata

@property (readonly, nonatomic) struct CGPoint { double x0; double x1; } position;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithPosition:(struct CGPoint { double x0; double x1; })position;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* BLSBacklightChangeSourceEventDisplayTapMetadata_h */
