//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightSceneVisualState_h
#define BLSBacklightSceneVisualState_h
@import Foundation;

#include "BSXPCCoding-Protocol.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSObject, NSString;

@interface BLSBacklightSceneVisualState : NSObject <BSXPCCoding, NSCopying, NSSecureCoding>

@property (readonly, nonatomic) long long activeAppearance;
@property (readonly, nonatomic) long long updateFidelity;
@property (readonly, nonatomic) long long adjustedLuminance;
@property (readonly, nonatomic) _Bool dimmed;
@property (readonly, nonatomic) long long grantedFidelity;
@property (readonly, nonatomic) long long expectedFidelity;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithActiveAppearance:(long long)appearance updateFidelity:(long long)fidelity adjustedLuminance:(long long)luminance;
- (id)initWithActiveAppearance:(long long)appearance updateFidelity:(long long)fidelity adjustedLuminance:(long long)luminance dimmed:(_Bool)dimmed;
- (id)init;
- (id)newVisualStateWithUpdateFidelity:(long long)fidelity;
- (id)bls_loggingString;
- (id)bls_shortLoggingString;
- (_Bool)isEqual:(id)equal;
- (_Bool)isEssentiallyEqualToVisualState:(id)state;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (_Bool)isDimmed;

@end

#endif /* BLSBacklightSceneVisualState_h */
