//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightSceneEnvironment_Private_Protocol_h
#define BLSBacklightSceneEnvironment_Private_Protocol_h
@import Foundation;

#include "BLSAlwaysOnSession.h"
#include "BLSBacklightSceneEnvironment-Protocol.h"
#include "BLSBacklightSceneEnvironmentUpdating-Protocol.h"

@class NSDate;

@protocol BLSBacklightSceneEnvironment_Private <BLSBacklightSceneEnvironment>

@required

@property (readonly) NSDate *presentationDate;
@property (retain) BLSAlwaysOnSession *alwaysOnSession;
@property _Bool animatingVisualState;
@property (retain) id <BLSBacklightSceneEnvironmentUpdating> updater;

/* required instance methods */
- (_Bool)isAnimatingVisualState;

@optional

@end

#endif /* BLSBacklightSceneEnvironment_Private_Protocol_h */
