//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightChangeEvent_h
#define BLSBacklightChangeEvent_h
@import Foundation;

#include "BLSBacklightChangeRequest.h"
#include "BSXPCCoding-Protocol.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSObject, NSString;

@interface BLSBacklightChangeEvent : NSObject <BSXPCCoding, NSCopying, NSSecureCoding>

@property (readonly, nonatomic) unsigned long long eventID;
@property (readonly, nonatomic) long long state;
@property (readonly, nonatomic) long long previousState;
@property (readonly, nonatomic) _Bool transitioning;
@property (readonly, nonatomic) BLSBacklightChangeRequest *changeRequest;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithEventID:(unsigned long long)id state:(long long)state previousState:(long long)state changeRequest:(id)request;
- (id)initWithEventID:(unsigned long long)id state:(long long)state previousState:(long long)state wasTransitioning:(_Bool)transitioning changeRequest:(id)request;
- (id)bls_shortLoggingString;
- (id)bls_loggingString;
- (_Bool)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (_Bool)wasTransitioning;

@end

#endif /* BLSBacklightChangeEvent_h */
