//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightSceneUpdateAnimationCompleteAction_h
#define BLSBacklightSceneUpdateAnimationCompleteAction_h
@import Foundation;

@class BSAction;

@interface BLSBacklightSceneUpdateAnimationCompleteAction : BSAction

/* instance methods */
- (id)initWithCompletion:(id /* block */)completion;

@end

#endif /* BLSBacklightSceneUpdateAnimationCompleteAction_h */
