//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightFBSSceneEnvironmentDiffAction_h
#define BLSBacklightFBSSceneEnvironmentDiffAction_h
@import Foundation;

#include "BLSBacklightFBSSceneEnvironmentDiffActionDelegate-Protocol.h"
#include "BLSBacklightSceneSettingsDiffInspector.h"

@class NSObject;

@interface BLSBacklightFBSSceneEnvironmentDiffAction : NSObject {
    /* instance variables */
    BLSBacklightSceneSettingsDiffInspector *_diffInspector;
}

@property (weak) id <BLSBacklightFBSSceneEnvironmentDiffActionDelegate> delegate;

/* instance methods */
- (void)performActionsForUpdatedFBSScene:(id)fbsscene settingsDiff:(id)diff fromSettings:(id)settings transitionContext:(id)context;

@end

#endif /* BLSBacklightFBSSceneEnvironmentDiffAction_h */
