//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightSceneUpdate_h
#define BLSBacklightSceneUpdate_h
@import Foundation;

#include "BLSBacklightSceneEnvironment_Private-Protocol.h"
#include "BLSBacklightSceneUpdateContext.h"

@class NSObject;

@interface BLSBacklightSceneUpdate : NSObject {
    /* instance variables */
    id /* block */ _sceneContentsUpdatedBlock;
    id /* block */ _performBacklightRampBlock;
    id /* block */ _sceneContentsAnimationCompleteBlock;
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
    _Bool _lock_sceneContentsUpdated;
    _Bool _lock_didStartBacklightRamp;
    _Bool _lock_animationComplete;
}

@property (readonly, nonatomic) _Bool isUpdateToDateSpecifier;
@property (readonly, weak, nonatomic) id <BLSBacklightSceneEnvironment_Private> environment;
@property (readonly, nonatomic) BLSBacklightSceneUpdateContext *context;
@property (readonly, nonatomic) _Bool sceneContentsUpdated;
@property (readonly, nonatomic) _Bool didStartBacklightRamp;
@property (readonly, nonatomic) _Bool animationComplete;

/* instance methods */
- (id)initForEnvironment:(id)environment visualState:(id)state previousVisualState:(id)state frameSpecifier:(id)specifier animated:(_Bool)animated triggerEvent:(id)event touchTargetable:(_Bool)targetable isUpdateToDateSpecifier:(_Bool)specifier sceneContentsUpdated:(id /* block */)updated performBacklightRamp:(id /* block */)ramp sceneContentsAnimationComplete:(id /* block */)complete;
- (id)description;
- (id)debugDescription;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (void)setReplacedSceneUpdate:(id)update;
- (_Bool)areSceneContentsUpdated;
- (void)sceneContentsDidUpdate;
- (void)performBacklightRampWithDuration:(double)duration;
- (_Bool)isAnimationComplete;
- (void)sceneContentsAnimationDidComplete;

@end

#endif /* BLSBacklightSceneUpdate_h */
