//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSBacklightStateObservable_Protocol_h
#define BLSBacklightStateObservable_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol BLSBacklightStateObservable <NSObject>

@required

@property (readonly, nonatomic) long long backlightState;
@property (readonly, nonatomic) long long flipbookState;
@property (readonly, nonatomic) _Bool transitioning;
@property (readonly, nonatomic) _Bool alwaysOnEnabled;
@property (readonly, nonatomic) _Bool deviceSupportsAlwaysOn;

/* required instance methods */
- (void)addObserver:(id)observer;
- (void)removeObserver:(id)observer;
- (_Bool)isTransitioning;
- (_Bool)isAlwaysOnEnabled;

@optional

@end

#endif /* BLSBacklightStateObservable_Protocol_h */
