//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSDesiredFidelityRequest_h
#define BLSDesiredFidelityRequest_h
@import Foundation;

@class NSObject;

@interface BLSDesiredFidelityRequest : NSObject {
    /* instance variables */
    id /* block */ _completion;
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
    _Bool _lock_completed;
}

/* instance methods */
- (id)initWithCompletion:(id /* block */)completion;
- (void)completeWithDesiredFidelity:(long long)fidelity;

@end

#endif /* BLSDesiredFidelityRequest_h */
