//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSDiagnosticsXPCHostInterface_Protocol_h
#define BLSDiagnosticsXPCHostInterface_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol BLSDiagnosticsXPCHostInterface <NSObject>

@required

/* required instance methods */
- (id)allFlipbookFrames;
- (id)frameOnGlassNow;
- (id)frameOnGlassWhenFlipbookLastCancelled;
- (void)surfaceForFrameUUID:(id)uuid reply:(id /* block */)reply;
- (void)rawSurfaceForFrameUUID:(id)uuid reply:(id /* block */)reply;

@optional

@end

#endif /* BLSDiagnosticsXPCHostInterface_Protocol_h */
