//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSFrameSpecifierModel_h
#define BLSFrameSpecifierModel_h
@import Foundation;

@class NSArray, NSMutableArray, NSObject;

@interface BLSFrameSpecifierModel : NSObject {
    /* instance variables */
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
    unsigned long long _stateHandler;
}

@property (readonly) NSArray *specifiers;
@property (readonly) unsigned long long specifierCount;

/* instance methods */
- (id)init;
- (void)dealloc;
- (id)description;
- (id)debugDescription;
- (void)addSpecifiers:(id)specifiers;
- (void)purgeAllButOneSpecifiersBeforeDate:(id)date;
- (void)purgeAllSpecifiersOnOrAfterDate:(id)date;
- (id)specifierAtPresentationDate:(id)date;

@end

#endif /* BLSFrameSpecifierModel_h */
