//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSPauseOnSystemSleepAttribute_h
#define BLSPauseOnSystemSleepAttribute_h
@import Foundation;

#include "BLSAttribute.h"

@interface BLSPauseOnSystemSleepAttribute : BLSAttribute

/* class methods */
+ (id)pauseOnSystemSleep;

/* instance methods */
- (_Bool)canBePaused;

@end

#endif /* BLSPauseOnSystemSleepAttribute_h */
