//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSPreventBacklightIdleAttribute_h
#define BLSPreventBacklightIdleAttribute_h
@import Foundation;

#include "BLSAttribute.h"
#include "BSXPCCoding-Protocol.h"

@class NSString;

@interface BLSPreventBacklightIdleAttribute : BLSAttribute <BSXPCCoding>

@property (readonly, nonatomic) _Bool restartTimerOnInvalidation;
@property (readonly, nonatomic) _Bool clearUserInteraction;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)preventIdle;
+ (id)preventIdleAndRestartTimerOnInvalidation;
+ (id)preventIdleClearUserInteractionAndRestartTimerOnInvalidation;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithRestartTimerOnInvalidation:(_Bool)invalidation clearUserInteraction:(_Bool)interaction;
- (_Bool)checkEntitlementSourceForRequiredEntitlements:(id)entitlements error:(out id *)error;
- (_Bool)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* BLSPreventBacklightIdleAttribute_h */
