//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSPresentationDateSpecifying_Protocol_h
#define BLSPresentationDateSpecifying_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@class NSArray, NSDate;

@protocol BLSPresentationDateSpecifying <NSObject>

@required

@property (readonly, nonatomic) NSDate *presentationDate;
@property (readonly, nonatomic) NSArray *specifiers;

/* required instance methods */
- (id)bls_loggingString;
- (id)bls_shortLoggingString;

@optional

@end

#endif /* BLSPresentationDateSpecifying_Protocol_h */
