//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef BLSRuntime_h
#define BLSRuntime_h
@import Foundation;

@class NSObject;

@interface BLSRuntime : NSObject

/* class methods */
+ (_Bool)isHostProcess;
+ (void)setIsHostProcess:(_Bool)process;

@end

#endif /* BLSRuntime_h */
