//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef NSDateInterval_BacklightServices_h
#define NSDateInterval_BacklightServices_h
@import Foundation;

@interface NSDateInterval (BacklightServices)

/* instance methods */
- (unsigned long long)bls_machContinuousStartTime;
- (unsigned long long)bls_machContinuousEndTime;
- (unsigned long long)bls_machDuration;
- (id)bls_initWithStartMachContinuousTime:(unsigned long long)time endMachContinuousTime:(unsigned long long)time;
- (_Bool)bls_containsDate:(id)date withEpsilon:(double)epsilon;
- (_Bool)bls_containsDate:(id)date withEpsilon:(double)epsilon outDelta:(double *)delta;
- (id)bls_loggingString;
- (id)bls_shortLoggingString;

@end

#endif /* NSDateInterval_BacklightServices_h */
