//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef NSDate_BacklightServices_h
#define NSDate_BacklightServices_h
@import Foundation;

@interface NSDate (BacklightServices)

/* instance methods */
- (unsigned long long)bls_machContinuousTime;
- (id)bls_initWithMachContinuousTime:(unsigned long long)time;
- (id)bls_initWithBSContinuousMachTime:(double)time;
- (id)bls_loggingString;
- (id)bls_shortLoggingString;
- (id)bls_fileNameString;
- (long long)bls_compare:(id)bls_compare withEpsilon:(double)epsilon;
- (_Bool)bls_isOnOrAfter:(id)after;
- (_Bool)bls_isOnOrBefore:(id)before;
- (_Bool)bls_isOnOrAfter:(id)after andOnOrBefore:(id)before;
- (_Bool)bls_isOnOrAfter:(id)after andOnOrBefore:(id)before withEpsilon:(double)epsilon;

@end

#endif /* NSDate_BacklightServices_h */
