//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef NSError_BacklightServices_h
#define NSError_BacklightServices_h
@import Foundation;

@interface NSError (BacklightServices)

/* instance methods */
- (id)bls_loggingString;
- (id)bls_shortLoggingString;

@end

#endif /* NSError_BacklightServices_h */
