//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef FBSMutableSceneClientSettings_BacklightServices_h
#define FBSMutableSceneClientSettings_BacklightServices_h
@import Foundation;

@interface FBSMutableSceneClientSettings (BacklightServices) <BLSBacklightSceneClientSettings>

/* instance methods */
- (void)bls_setHasDelegate:(_Bool)delegate;
- (void)bls_setSupportsAlwaysOn:(_Bool)on;
- (void)bls_setOptsOutOfProcessAssertions:(_Bool)assertions;

@end

#endif /* FBSMutableSceneClientSettings_BacklightServices_h */
