//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 4.5.3.0.0
//
#ifndef FBSSceneSettings_BacklightServices_h
#define FBSSceneSettings_BacklightServices_h
@import Foundation;

@interface FBSSceneSettings (BacklightServices) <BLSBacklightSceneSettings>

/* instance methods */
- (_Bool)bls_isDelegateActive;
- (id)bls_visualState;
- (id)bls_presentationDate;
- (_Bool)bls_isAlwaysOnEnabledForEnvironment;
- (unsigned long long)bls_renderSeed;
- (_Bool)bls_isLiveUpdating;
- (_Bool)bls_hasUnrestrictedFramerateUpdates;

@end

#endif /* FBSSceneSettings_BacklightServices_h */
