#include "AGAttribute.h"
#include "AGAttributeFlags.h"
#include "AGAttributeInfo.h"
#include "AGAttributeType.h"
#include "AGAttributeTypeFlags.h"
#include "AGBase.h"
#include "AGCachedValueOptions.h"
#include "AGChangedValueFlags.h"
#include "AGComparison.h"
#include "AGCounterQueryType.h"
#include "AGDebugServer.h"
#include "AGGraph.h"
#include "AGGraphContext.h"
#include "AGGraphDescription.h"
#include "AGGraphTracing.h"
#include "AGInputOptions.h"
#include "AGSearchOptions.h"
#include "AGSubgraph.h"
#include "AGTupleType.h"
#include "AGTypeID.h"
#include "AGUniqueID.h"
#include "AGValue.h"
#include "AGValueOptions.h"
#include "AGValueState.h"
#include "AGVersion.h"
#include "AGWeakAttribute.h"

AG_EXPORT double AttributeGraphVersionNumber;
AG_EXPORT const unsigned char AttributeGraphVersionString[];
